# Generated by Django 5.2 on 2025-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("excerpt", models.TextField(blank=True, verbose_name="Tóm tắt ngắn")),
                ("content", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "image",
                    models.ImageField(
                        upload_to="blog_images/", verbose_name="Ảnh đại diện"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="Chăm Sóc Da", max_length=100, verbose_name="Chuyên mục"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Admin", max_length=100, verbose_name="Tác giả"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc"),
                ),
            ],
            options={
                "verbose_name": "Bài viết",
                "verbose_name_plural": "Bài viết",
                "ordering": ["-created_at"],
            },
        ),
    ]
