# Generated by Django 5.2 on 2025-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("detail", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("rating", models.FloatField(default=5.0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                (
                    "vouchers",
                    models.CharField(
                        blank=True,
                        help_text="Cách nhau bởi dấu phẩy, ví dụ: GIAM10K,FREESHIP",
                        max_length=255,
                    ),
                ),
                ("combo", models.CharField(blank=True, max_length=255)),
                ("shipping", models.CharField(blank=True, max_length=255)),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Mỗi dòng là một tính năng nổi bật"
                    ),
                ),
                ("ingredients", models.TextField(blank=True)),
                ("how_to_use", models.TextField(blank=True)),
                ("reviews", models.TextField(blank=True)),
                (
                    "faqs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách câu hỏi & trả lời. VD: [{'question': 'Q?', 'answer': 'A.'}]",
                    ),
                ),
                (
                    "recommendations",
                    models.ManyToManyField(
                        blank=True, related_name="recommended_by", to="products.product"
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="products.product"
                    ),
                ),
            ],
        ),
    ]
