# Generated by Django 5.2 on 2025-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(
                choices=[
                    ("best_seller", "Best Seller"),
                    ("new", "New Arrival"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Gắn nhãn để hiển thị ở mục đặc biệt (Best Seller, New Arrival)",
                max_length=20,
            ),
        ),
    ]
