<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-14 11:30
=======
# Generated by Django 5.2.1 on 2025-05-14 11:31
>>>>>>> 3b6699afe0c640a8fe410f5e92c7f2e0aef07310

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(
                choices=[
                    ("best_seller", "Best Seller"),
                    ("new", "New Arrival"),
                    ("other", "Other"),
                    ("models", "Models"),
                ],
                default="other",
                help_text="Gắn nhãn để hiển thị ở mục đặc biệt (Best Seller, New Arrival)",
                max_length=20,
            ),
        ),
    ]
