# Generated by Django 5.2 on 2025-05-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_virtualanalysis_delete_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
