# Generated by Django 5.2 on 2025-05-14 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_virtualanalysis_is_active"),
        ("products", "0003_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialoffer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="specialoffer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="specialoffer",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_input",
                    models.JSONField(
                        help_text="Danh sách câu trả lời từ người dùng (7 câu)"
                    ),
                ),
                (
                    "ai_recommendation",
                    models.TextField(help_text="Phân tích tổng hợp từ AI"),
                ),
                (
                    "keywords",
                    models.JSONField(
                        help_text="Các từ khóa liên quan đến sản phẩm gợi ý"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Các sản phẩm được AI gợi ý dựa trên từ khóa",
                        related_name="analysis_results",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
