# Generated by Django 5.2 on 2025-05-14 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_specialoffer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
