# Generated by Django 5.2 on 2025-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_blog_options_blog_excerpt_alter_blog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="consent",
            field=models.BooleanField(default=False),
        ),
    ]
