# Generated by Django 5.2 on 2025-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_district_remove_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Thanh toán khi nhận hàng (COD)"),
                    ("bank", "Chuyển khoản ngân hàng"),
                    ("momo", "Ví MoMo"),
                ],
                default="cod",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="province",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="ward",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_detail",
            field=models.CharField(default="", max_length=255),
        ),
    ]
